# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gmc_tvp_main.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 480)
        MainWindow.setMinimumSize(QtCore.QSize(800, 480))
        MainWindow.setMaximumSize(QtCore.QSize(800, 480))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frameTarget = QtWidgets.QFrame(self.centralwidget)
        self.frameTarget.setGeometry(QtCore.QRect(190, 150, 351, 161))
        self.frameTarget.setStyleSheet("background-color: rgb(25, 255, 0);")
        self.frameTarget.setFrameShape(QtWidgets.QFrame.Box)
        self.frameTarget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameTarget.setLineWidth(2)
        self.frameTarget.setMidLineWidth(0)
        self.frameTarget.setObjectName("frameTarget")
        self.lbTarget = QtWidgets.QLabel(self.frameTarget)
        self.lbTarget.setGeometry(QtCore.QRect(10, 10, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbTarget.setFont(font)
        self.lbTarget.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lbTarget.setObjectName("lbTarget")
        self.txtTarget = QtWidgets.QLabel(self.frameTarget)
        self.txtTarget.setGeometry(QtCore.QRect(10, 40, 331, 111))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.txtTarget.setFont(font)
        self.txtTarget.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.txtTarget.setObjectName("txtTarget")
        self.frameInput = QtWidgets.QFrame(self.centralwidget)
        self.frameInput.setGeometry(QtCore.QRect(190, 90, 351, 51))
        self.frameInput.setFrameShape(QtWidgets.QFrame.Box)
        self.frameInput.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameInput.setLineWidth(2)
        self.frameInput.setMidLineWidth(0)
        self.frameInput.setObjectName("frameInput")
        self.btnInput = QtWidgets.QPushButton(self.frameInput)
        self.btnInput.setGeometry(QtCore.QRect(10, 10, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnInput.setFont(font)
        self.btnInput.setFlat(True)
        self.btnInput.setObjectName("btnInput")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(560, 90, 231, 111))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setLineWidth(2)
        self.frame_5.setMidLineWidth(0)
        self.frame_5.setObjectName("frame_5")
        self.lbCycleCounter = QtWidgets.QLabel(self.frame_5)
        self.lbCycleCounter.setGeometry(QtCore.QRect(10, 10, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbCycleCounter.setFont(font)
        self.lbCycleCounter.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lbCycleCounter.setObjectName("lbCycleCounter")
        self.txtCycleCounter = QtWidgets.QLabel(self.frame_5)
        self.txtCycleCounter.setGeometry(QtCore.QRect(10, 50, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.txtCycleCounter.setFont(font)
        self.txtCycleCounter.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.txtCycleCounter.setObjectName("txtCycleCounter")
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(560, 210, 231, 101))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setLineWidth(2)
        self.frame_6.setMidLineWidth(0)
        self.frame_6.setObjectName("frame_6")
        self.lbTq = QtWidgets.QLabel(self.frame_6)
        self.lbTq.setGeometry(QtCore.QRect(10, 10, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbTq.setFont(font)
        self.lbTq.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lbTq.setObjectName("lbTq")
        self.txtTq = QtWidgets.QLabel(self.frame_6)
        self.txtTq.setGeometry(QtCore.QRect(10, 50, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.txtTq.setFont(font)
        self.txtTq.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.txtTq.setObjectName("txtTq")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(560, 10, 231, 71))
        self.label_10.setStyleSheet("border-image: url(:/img/kubotalogo.png);")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("../GMC_TVP/kubotalogo.png"))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.btnSetting = QtWidgets.QPushButton(self.centralwidget)
        self.btnSetting.setGeometry(QtCore.QRect(710, 390, 71, 71))
        self.btnSetting.setAutoFillBackground(False)
        self.btnSetting.setStyleSheet("border-image: url(:/img/setting.png);")
        self.btnSetting.setText("")
        self.btnSetting.setObjectName("btnSetting")
        self.frameActual = QtWidgets.QFrame(self.centralwidget)
        self.frameActual.setGeometry(QtCore.QRect(190, 310, 351, 161))
        self.frameActual.setStyleSheet("background-color: rgb(25, 255, 0);")
        self.frameActual.setFrameShape(QtWidgets.QFrame.Box)
        self.frameActual.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameActual.setLineWidth(2)
        self.frameActual.setMidLineWidth(0)
        self.frameActual.setObjectName("frameActual")
        self.lbActual = QtWidgets.QLabel(self.frameActual)
        self.lbActual.setGeometry(QtCore.QRect(10, 10, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbActual.setFont(font)
        self.lbActual.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lbActual.setObjectName("lbActual")
        self.txtActual = QtWidgets.QLabel(self.frameActual)
        self.txtActual.setGeometry(QtCore.QRect(10, 40, 331, 111))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.txtActual.setFont(font)
        self.txtActual.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.txtActual.setObjectName("txtActual")
        self.frameNG = QtWidgets.QFrame(self.centralwidget)
        self.frameNG.setGeometry(QtCore.QRect(10, 340, 161, 131))
        self.frameNG.setStyleSheet("background-color: rgb(255, 25, 0);")
        self.frameNG.setFrameShape(QtWidgets.QFrame.Box)
        self.frameNG.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameNG.setLineWidth(2)
        self.frameNG.setMidLineWidth(0)
        self.frameNG.setObjectName("frameNG")
        self.btnNG = QtWidgets.QPushButton(self.frameNG)
        self.btnNG.setGeometry(QtCore.QRect(10, 10, 141, 111))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.btnNG.setFont(font)
        self.btnNG.setFlat(True)
        self.btnNG.setObjectName("btnNG")
        self.frameOK = QtWidgets.QFrame(self.centralwidget)
        self.frameOK.setGeometry(QtCore.QRect(10, 180, 161, 131))
        self.frameOK.setStyleSheet("background-color: rgb(25, 255, 0);")
        self.frameOK.setFrameShape(QtWidgets.QFrame.Box)
        self.frameOK.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameOK.setLineWidth(2)
        self.frameOK.setMidLineWidth(0)
        self.frameOK.setObjectName("frameOK")
        self.btnOK = QtWidgets.QPushButton(self.frameOK)
        self.btnOK.setGeometry(QtCore.QRect(10, 10, 141, 111))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.btnOK.setFont(font)
        self.btnOK.setFlat(True)
        self.btnOK.setObjectName("btnOK")
        self.frameCycleComplete = QtWidgets.QFrame(self.centralwidget)
        self.frameCycleComplete.setGeometry(QtCore.QRect(10, 90, 161, 81))
        self.frameCycleComplete.setStyleSheet("background-color: rgb(245, 121, 0);")
        self.frameCycleComplete.setFrameShape(QtWidgets.QFrame.Box)
        self.frameCycleComplete.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameCycleComplete.setLineWidth(2)
        self.frameCycleComplete.setMidLineWidth(0)
        self.frameCycleComplete.setObjectName("frameCycleComplete")
        self.btnCycleComplete = QtWidgets.QPushButton(self.frameCycleComplete)
        self.btnCycleComplete.setGeometry(QtCore.QRect(10, 10, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnCycleComplete.setFont(font)
        self.btnCycleComplete.setFlat(True)
        self.btnCycleComplete.setObjectName("btnCycleComplete")
        self.frameInput_2 = QtWidgets.QFrame(self.centralwidget)
        self.frameInput_2.setGeometry(QtCore.QRect(10, 10, 531, 61))
        self.frameInput_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frameInput_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameInput_2.setLineWidth(2)
        self.frameInput_2.setMidLineWidth(0)
        self.frameInput_2.setObjectName("frameInput_2")
        self.lbApplication = QtWidgets.QLabel(self.frameInput_2)
        self.lbApplication.setGeometry(QtCore.QRect(10, 10, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbApplication.setFont(font)
        self.lbApplication.setObjectName("lbApplication")
        self.btnApplication = QtWidgets.QPushButton(self.frameInput_2)
        self.btnApplication.setGeometry(QtCore.QRect(160, 10, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnApplication.setFont(font)
        self.btnApplication.setFlat(True)
        self.btnApplication.setObjectName("btnApplication")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(560, 320, 231, 31))
        self.progressBar.setStyleSheet("color: rgb(245, 121, 0);")
        self.progressBar.setMaximum(20000)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setObjectName("progressBar")
        self.btnLogo = QtWidgets.QPushButton(self.centralwidget)
        self.btnLogo.setGeometry(QtCore.QRect(560, 390, 71, 71))
        self.btnLogo.setAutoFillBackground(False)
        self.btnLogo.setStyleSheet("border-image: url(:/img/joinmaxlogo2.png);")
        self.btnLogo.setText("")
        self.btnLogo.setObjectName("btnLogo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.lbTarget.setBuddy(self.lbTarget)
        self.txtTarget.setBuddy(self.txtTarget)
        self.lbActual.setBuddy(self.lbTarget)
        self.txtActual.setBuddy(self.txtTarget)
        self.lbApplication.setBuddy(self.lbTarget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbTarget.setText(_translate("MainWindow", "Target"))
        self.txtTarget.setText(_translate("MainWindow", "0"))
        self.btnInput.setText(_translate("MainWindow", "1234"))
        self.lbCycleCounter.setText(_translate("MainWindow", "Cycle Counter"))
        self.txtCycleCounter.setText(_translate("MainWindow", "00000"))
        self.lbTq.setText(_translate("MainWindow", "TQ                NM"))
        self.txtTq.setText(_translate("MainWindow", "-"))
        self.lbActual.setText(_translate("MainWindow", "Actual"))
        self.txtActual.setText(_translate("MainWindow", "0"))
        self.btnNG.setText(_translate("MainWindow", "NG"))
        self.btnOK.setText(_translate("MainWindow", "OK"))
        self.btnCycleComplete.setText(_translate("MainWindow", "Cycle\n"
"Complete"))
        self.lbApplication.setText(_translate("MainWindow", "Application :"))
        self.btnApplication.setText(_translate("MainWindow", "Default"))
import resource_rc
